# coding: utf-8

# flake8: noqa
"""
    jans-config-api

    jans-config-api - Authorization services  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: xxx@gluu.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.address import Address
from swagger_client.models.any_value import AnyValue
from swagger_client.models.app_configuration import AppConfiguration
from swagger_client.models.auth_health_status import AuthHealthStatus
from swagger_client.models.authentication_filters import AuthenticationFilters
from swagger_client.models.authentication_method import AuthenticationMethod
from swagger_client.models.authentication_protection_configuration import AuthenticationProtectionConfiguration
from swagger_client.models.base_resource import BaseResource
from swagger_client.models.basic_list_response import BasicListResponse
from swagger_client.models.ciba_end_user_notification_config import CIBAEndUserNotificationConfig
from swagger_client.models.cache_configuration import CacheConfiguration
from swagger_client.models.client import Client
from swagger_client.models.client_attributes import ClientAttributes
from swagger_client.models.cors_configuration_filter import CorsConfigurationFilter
from swagger_client.models.couchbase_configuration import CouchbaseConfiguration
from swagger_client.models.custom_attribute import CustomAttribute
from swagger_client.models.custom_script import CustomScript
from swagger_client.models.email import Email
from swagger_client.models.entitlement import Entitlement
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.fido2_configuration import Fido2Configuration
from swagger_client.models.gluu_attribute import GluuAttribute
from swagger_client.models.gluu_attribute_attribute_validation import GluuAttributeAttributeValidation
from swagger_client.models.group import Group
from swagger_client.models.health_status import HealthStatus
from swagger_client.models.health_status_item import HealthStatusItem
from swagger_client.models.in_memory_configuration import InMemoryConfiguration
from swagger_client.models.instant_messaging_address import InstantMessagingAddress
from swagger_client.models.jans_fido2_dyn_configuration import JansFido2DynConfiguration
from swagger_client.models.json_web_key import JsonWebKey
from swagger_client.models.ldap_configuration import LdapConfiguration
from swagger_client.models.logging_configuration import LoggingConfiguration
from swagger_client.models.memcached_configuration import MemcachedConfiguration
from swagger_client.models.meta import Meta
from swagger_client.models.name import Name
from swagger_client.models.native_persistence_configuration import NativePersistenceConfiguration
from swagger_client.models.patch_request import PatchRequest
from swagger_client.models.persistence_configuration import PersistenceConfiguration
from swagger_client.models.phone_number import PhoneNumber
from swagger_client.models.photo import Photo
from swagger_client.models.redis_configuration import RedisConfiguration
from swagger_client.models.requested_parties import RequestedParties
from swagger_client.models.role import Role
from swagger_client.models.scim_patch_operation import ScimPatchOperation
from swagger_client.models.scim_patch_request import ScimPatchRequest
from swagger_client.models.scope import Scope
from swagger_client.models.scope_attributes import ScopeAttributes
from swagger_client.models.script_error import ScriptError
from swagger_client.models.search_request import SearchRequest
from swagger_client.models.sector_identifier import SectorIdentifier
from swagger_client.models.simple_custom_property import SimpleCustomProperty
from swagger_client.models.simple_extended_custom_property import SimpleExtendedCustomProperty
from swagger_client.models.smtp_configuration import SmtpConfiguration
from swagger_client.models.sql_configuration import SqlConfiguration
from swagger_client.models.stat_response_item import StatResponseItem
from swagger_client.models.token_map_object import TokenMapObject
from swagger_client.models.uma_resource import UmaResource
from swagger_client.models.user_list_response import UserListResponse
from swagger_client.models.user_resource import UserResource
from swagger_client.models.web_keys_configuration import WebKeysConfiguration
from swagger_client.models.x509_certificate import X509Certificate
